name: "Wooden Furnace Addon"
version: "1.1.5"
slug: "wooden_furnace"
description: "Temperature monitoring for your wooden furnace."
panel_icon: "mdi:gas-burner"

arch:
  - aarch64
  - amd64
  - armhf
  - armv7

startup: application
boot: auto

ingress: true
ingress_port: 8080
ports:
  8080/tcp: 8080

hassio_api: true
homeassistant_api: true
hassio_role: default

options:
  sensor_groups: ""
  database_url: "/data/db.sqlite"
  filter_target_pps: 500
  filter_window_size: 5

schema:
  sensor_groups: str
  database_url: str
  filter_target_pps: "int(10,1000)"
  filter_window_size: "int(2,50)"
